### ISSUE TITLE
Various Issues and Questions

### ISSUE THREAD

**Issue by BrekiTomasson** [maxheyn/slapmap#1]
Reworded from the original post in the pull request on kalronline/slapmpap 

Your version of slapmap allows people to endlessly create amethyst shards, at least when I'm testing it (so it might be a conflict with another mod). Basically, create a slap, place it, and then punch it out with your fists, and it drops the map and an amethyst shard for some reason.

Also, if you're already making changes to the mod, might I suggest that it defaults to some reasonable height/width if nothing is stated? Say, maybe it figures out which edge of the image given is the longest and then does `width=2` if it's an image in landscape orientation or `height=2` if it's an image in portrait orientation?

**Comment by maxheyn** [comment]
Could you test it without any other mods? When I test it on my server, I cannot reproduce this issue.
I recorded this video about an hour before this issue for the readme and you can see around the 12 second mark that this didn't occur for me. https://user-images.githubusercontent.com/16215993/137979370-9f8b4977-a29e-4e66-826a-d51290bec580.mp4

I'll see if I can figure out the image restrictions, sure.

**Comment by BrekiTomasson** [comment]
I found the problem with the amethyst shard; but it boils down to a problem with `slapmap` nonetheless. The amethyst shard was being generated by the mod `charm`, which allows you to right click an amethyst onto an item frame to make it invisible. Breaking the item frame will then drop both the item frame and the amethyst.

Installing `slapmap` allows you to place maps (any maps!) directly onto walls, and it automatically generates the item frames for you. This means that you can use `slapmap` to generate an infinite amount of item frames by creating a map, placing it directly on a wall, and then removing it again. The extra amethyst was just something generated by `charm` because it saw the item frame that slapmap generated as an invisible item frame.

**Comment by maxheyn** [comment]
That sounds more like an issue with `charm`. It should be on `charm`'s end to apply a tag to the item frame if it was made invisible with an amethyst, rather than just assuming that every item frame that was invisible contains an amethyst in it. If `charm` is the one generating the amethysts from the invisible item frames, it is not an issue with `slapmap`.

This implies that `charm` would do the same thing with any other method that can make an item frame invisible.

**Comment by BrekiTomasson** [comment]
It doesn't look like you read my entire message. Even with `charm` turned off, I can still place **any** map directly onto a wall, even without an item frame, and then break the map and generate an item frame. That's an issue with `slapmap` as this behavior disappears as soon as I disable `slapmap`.

**Comment by maxheyn** [comment]
Ah okay, I misunderstood that 2nd part. Yeah I was able to reproduce that. I'll see if I can do anything about it.

**Comment by maxheyn** [comment]
Here, I just played around a little bit and tried something out. I think I fixed the issue. Here's a video of it below. Not getting any item frames from the generated maps and it still seems to work with normal maps. I also can't right-click with any map to place it down anymore.

https://user-images.githubusercontent.com/16215993/138011067-d6e82c0f-1e2b-48a7-a8ca-5f0ef257121d.mp4

Mind trying it out yourself over here? https://github.com/maxheyn/slapmap/releases/download/v1.0.3/slapmap-1.0.3.jar

**Comment by BrekiTomasson** [comment]
Yup, that looks like it did the trick!

That said, I did find one more issue when testing it. Placing a slap and then punching it off of the wall, the maps aren't locked. Holding the map and running around has it looking like this:

![image](https://user-images.githubusercontent.com/7026735/138017319-5421a6c1-7d4b-41f3-ac91-3444ca1f7b66.png)

Note the green plains area over by the top left corner, that wasn't in the original image.

**Comment by maxheyn** [comment]
Did some looking into it and I couldn't figure out how to lock the maps in the code. I'll keep looking though but it's not a super huge priority.

**Comment by maxheyn** [comment]
Will be tracking this here https://github.com/maxheyn/slapmap/issues/2

**Comment by maxheyn** [comment]
@BrekiTomasson fixed these issues in https://github.com/maxheyn/slapmap/issues/2 and released a new version here https://github.com/maxheyn/slapmap/releases/tag/v1.1.0
